### ISSUE TITLE
how i'm suppose to run this plugin?

### ISSUE THREAD

**Issue by hadasafe** [thoersch/new-relic-cassandra#2]
there is no Description !

**Comment by thoersch** [comment]
Did you look at the lengthy readme?  It tells you all the requirements, how to setup it up, link it to you NR account, etc...

From there, it's no different from any other NR plugin. If this is your first plugin, please read their documentation: https://docs.newrelic.com/docs/plugins/plugins-new-relic/installing-plugins/java-plugin-installation-example

If you still are having issues after reading both, please reopen.
