### ISSUE TITLE
cassandra 3.0 support

### ISSUE THREAD

**Issue by postmart** [thoersch/new-relic-cassandra#6]
Is this plugin supposed to work with cassandra 3 as well?
I am getting the following error:

```
[2015-12-24 08:39:48,762] ERROR com.tylerhoersch.nr.cassandra.templates.Cassandra2xMetrics - Error polling for metrics:javax.management.AttributeNotFoundException: No such attribute: LatencyUnit
```

Any plans for supporting ver 3?

Thanks!

**Comment by thoersch** [comment]
Looking into this now

**Comment by vankhoa011** [comment]
+1 same error  with cassandra 2.2.5

**Comment by kyxap1** [comment]
Cassandra 2.2.1
[2016-04-27 21:01:48,465] ERROR com.tylerhoersch.nr.cassandra.templates.Cassandra2xMetrics - Error polling for metrics:javax.management.AttributeNotFoundException: No such attribute: LatencyUnit

**Comment by thoersch** [comment]
@vankhoa011 and @kyxap1 your issues should now be resolved.  It also might work for the overall issue of 3x, but I'm going to do further testing before closing it out. Let me know if you have any issues with the new version.

**Comment by thoersch** [comment]
@postmart tested against 3.0.2 and works with latest merge.  Continuing to develop the 3xsupport branch for a cleaner solution longer term.

**Comment by XIAOFENGYU** [comment]
@thoersch Do you have any estimated timeline on 3x support? Thanks!

**Comment by thoersch** [comment]
@XIAOFENGYU the latest release will work with 3x. Was there something specifically you were looking for?

**Comment by XIAOFENGYU** [comment]
@thoersch Thanks for you response. We are investigating on monitoring Cassandra on newrelic, basically, we will probably use Cassandra 3.X.  We don't have specific requirement yet for now.  One thing we might be interested in is the crossNodeLatency in a deployment with 2 DCs.
